language: go
go:
  - 1.2
before_install:
  - go get github.com/franela/goblin
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -package ./server qmLv9EH7njGv8axqEYO1usHnnPISqCYNs